# Generated by Django 4.2.1 on 2023-08-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='series',
            fields=[
                ('id_serie', models.AutoField(primary_key=True, serialize=False)),
                ('serie', models.CharField(max_length=75)),
                ('url', models.URLField()),
            ],
        ),
    ]
