# Generated by Django 4.2.4 on 2023-09-16 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Easser_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='series',
        ),
    ]
