# Generated by Django 4.2.4 on 2023-09-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Easser_app', '0002_delete_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id_serie', models.AutoField(primary_key=True, serialize=False)),
                ('serie', models.CharField(max_length=75)),
                ('url', models.URLField()),
            ],
        ),
    ]
